services:
  - type: web
    name: my-express-app
    env: node
    repo: https://github.com/arpan-maruti/backend-medical-record-management
    branch: main
    buildCommand: npm install
    startCommand: node server.js
